'use strict';
module.exports={title:'ModelConnect · Model Capabilities',capabilities:[
  {id:'dictation',title:'Speech Recognition',english:'ASR → THINKING',modality:'Audio → transcript → refined text',models:['Speech Recognition Model','Thinking Model'],description:'Turn speech into text, then resolve spoken corrections and improve the wording. Inspect each model step separately.',family:'whisper + qwen',task:'ITranscription → ITextGeneration',stages:['Record or import audio','Original transcript','Refine with Thinking'],reference:'Voice input, dictation and hands-free writing',boundary:'Speech recognition and text refinement use separate models. The original transcript stays visible. Word timestamps and speaker identification are not included.'},
  {id:'reasoning',title:'Reasoning',english:'REASONING',modality:'Question → reasoning → answer',models:['Reasoning Model'],description:'Ask the same question with Thinking off and on. Compare the actual answers, reasoning output and computation cost.',family:'qwen',task:'ITextGeneration · enable_thinking',stages:['Enter a constraint problem','Direct answer or Thinking','Compare answers and timing'],reference:'Planning, problem solving and complex instructions',sample:'Schedule Alice, Ben and Casey for three consecutive demos, one demo per person. Alice cannot go first. Ben must go before Casey. Casey cannot go last. Give the unique order and briefly check each constraint. Reason and answer in English. Keep the final answer concise.',boundary:'The switch changes the actual model configuration. The reasoning text comes from the model. Thinking can use more time and tokens, and does not guarantee a correct answer.'},
  {id:'embedding',title:'Semantic Search',english:'EMBEDDING',modality:'Text → vectors → similarity',models:['Embedding Model'],description:'Match meaning with real 384-dimensional vectors. Change a query to see the ranking and similarity matrix respond.',family:'bert',task:'IEmbedding',stages:['Enter query and candidates','Encode semantic vectors','Rank by cosine similarity'],reference:'Semantic search, knowledge retrieval and content discovery',sample:'My laptop cannot get online.',documents:['The computer cannot connect to Wi-Fi. Check the wireless network settings.','Troubleshooting an internet connection on a portable computer.','How to export notes as a text document.','Ingredients for cooking tomato and egg noodles tonight.','Find a hotel that welcomes pets.'],boundary:'The model encodes the text into vectors. The application computes ranking and cosine similarity from those vectors. Similarity is not an accuracy score or a probability.'},
  {id:'vision',title:'Image Segmentation',english:'IMAGE SEGMENTATION',modality:'Image + point → object mask',models:['Segmentation Model'],description:'Click an object and let the vision model predict its boundary. Inspect the mask and export a transparent cutout.',family:'sam',task:'IPointPromptedSegmentation',stages:['Choose an image','Click an object','Inspect mask and cutout'],reference:'Image editing, object selection and visual creation',boundary:'Each click runs an independent segmentation request with one point. The result uses the highest-scoring model candidate. The mask is predicted by the model.'},
  {id:'understanding',title:'Image Understanding',english:'VISION + LANGUAGE',modality:'Image + question → grounded answer',models:['Image Understanding Model'],description:'Ask a model what it sees. Change the question or image and inspect how the answer responds.',family:'qwen_vl',task:'IVisionLanguageGeneration',stages:['Choose an image','Ask a visual question','Read the model answer'],reference:'Visual assistance, photo understanding and image-based questions',sample:'What color is the car in this image?',boundary:'The model generates text from image pixels and your question. Answers may contain mistakes. This demo does not provide verified text locations or operate other applications.'},
  {id:'geometry',title:'Image to Depth',english:'DEPTH + 3D POINTS',modality:'Single image → depth → 3D points',models:['Depth Model'],description:'See a model infer the shape of a scene from one photo. Explore its depth map and rotate the predicted points.',family:'moge',task:'IMonocularGeometry',stages:['Choose a scene','Predict per-pixel geometry','Explore depth and 3D points'],reference:'Spatial perception, scene understanding and 3D-aware visual effects',boundary:'Depth, points, validity and camera parameters come from the model. The app colors the depth and draws a sampled preview. A single-image prediction is not a verified real-world measurement or a complete 3D reconstruction.'},
  {id:'voice',title:'Realtime Voice',english:'SPEECH TO SPEECH',modality:'Voice input ⇄ generated voice',models:['Speech Model'],description:'Speak with a multimodal model and hear its generated reply. Observe the input transcript, response text and audio.',family:'nemotron_voicechat',task:'ISpeechSessionProvider',stages:['Microphone input at 16 kHz','Understand and respond','Generated audio at 48 kHz'],reference:'Voice interfaces, conversational assistants and interactive experiences',sample:'What is the capital city of France?',boundary:'This uses a speech-to-speech model. It is separate from the speech recognition and text refinement chain. This demo is qualified for short English exchanges.'}
]};
